# docker-compose.yml

version: '3.8'

services:
  app:
    build: ./api/    
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: Gerador-certificado-gs-cp6
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Gerador-certificado-gs-cp6
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Porta para comunicação com RabbitMQ
      - "15672:15672" # Interface de gerenciamento do RabbitMQ

volumes:
  mysql-data:
