version: '3.8'

services:
  app:
    build: ./api/
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: Gerador-certificado-gs-cp6
      RABBITMQ_URL: amqp://rabbitmq
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Gerador-certificado-gs-cp6
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
